import { type Config } from 'tailwindcss'

export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}'
  ],
  theme: {
    extend: {},
    // Generated by https://coolors.co/242331-533e2d-a27035-b88b4a-ddca7d
    colors: {
      raisin_black: {
        DEFAULT: '#242331',
        100: '#07070a',
        200: '#0e0e13',
        300: '#15141d',
        400: '#1c1b26',
        500: '#242331',
        600: '#474562',
        700: '#6c6994',
        800: '#9d9bb8',
        900: '#cecddb'
      },
      cafe_noir: {
        DEFAULT: '#533e2d',
        100: '#110c09',
        200: '#211912',
        300: '#32251b',
        400: '#423124',
        500: '#533e2d',
        600: '#856347',
        700: '#af896a',
        800: '#c9b09c',
        900: '#e4d8cd'
      },
      golden_brown: {
        DEFAULT: '#a27035',
        100: '#20160a',
        200: '#412c15',
        300: '#61421f',
        400: '#81592a',
        500: '#a27035',
        600: '#c58d4c',
        700: '#d4a979',
        800: '#e2c6a6',
        900: '#f1e2d2'
      },
      lion: {
        DEFAULT: '#b88b4a',
        100: '#251c0f',
        200: '#4b381d',
        300: '#70542c',
        400: '#96703a',
        500: '#b88b4a',
        600: '#c7a26f',
        700: '#d5ba93',
        800: '#e3d1b7',
        900: '#f1e8db'
      },
      citron: {
        DEFAULT: '#ddca7d',
        100: '#372f0e',
        200: '#6e5e1c',
        300: '#a58d2b',
        400: '#cfb446',
        500: '#ddca7d',
        600: '#e4d597',
        700: '#ebdfb1',
        800: '#f2eacb',
        900: '#f8f4e5'
      }
    }
  },
  plugins: []
} satisfies Config
