env:
  browser: true
  es2021: true
  node: true
extends:
  - standard-with-typescript
  - plugin:react/recommended
  - plugin:deprecation/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/strict-type-checked
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
settings:
  react:
    version: "18.2"
ignorePatterns:
  - "**/*.generated.ts"
rules:
  sort-imports:
    - warn
    - allowSeparatedGroups: true
      memberSyntaxSortOrder: [all, multiple, single, none]
  import/order:
    - warn
    - newlines-between: always
  import/consistent-type-specifier-style:
    - warn
    - prefer-inline
  # Assigning any is needed when working with JSON or YAML
  # The any type can't be returned due to explicit return types and no explicit any
  "@typescript-eslint/no-unsafe-assignment": off
  "@typescript-eslint/no-explicit-any": warn
  "@typescript-eslint/consistent-type-assertions":
    - warn
    - { assertionStyle: never }
