# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

# Consider errors non blocking to the CI
# TODO: May want to disable this once we have a good handle on the errors
DISABLE_ERRORS: true

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
# ENABLE_LINTERS:

DISABLE_LINTERS:
  # These are handled by the eslint workflow
  - JAVASCRIPT_ES
  - TYPESCRIPT_ES
  - JSX_ESLINT
  - TSX_ESLINT
  - JAVASCRIPT_STANDARD
  - TYPESCRIPT_STANDARD

  # HTML is only present to load the React app
  - HTML_HTMLHINT

  # cSpell is handled through a vscode test task
  - SPELL_CSPELL
  - SPELL_LYCHEE

  # This is designed for Transact-SQL, not SQLite
  - SQL_TSQLLINT

# DISABLE:
# - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
# - SPELL # Uncomment to disable checks of spelling mistakes

# tsconfig.json allows comments
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: tsconfig\.json

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false
# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true
