env:
  commonjs: true
  es2021: true
  node: true
extends: standard-with-typescript
parserOptions:
  ecmaVersion: latest
ignorePatterns:
  - "*.generated.ts"
rules:
  sort-imports:
   - warn
   - allowSeparatedGroups: true
  import/order:
   - warn
   - newlines-between: always
  import/consistent-type-specifier-style:
   - warn
   - prefer-inline
