openapi: 3.0.0

info:
  title: CHEF Backend API
  version: 1.0.0

tags:
  - name: Fridge
  - name: Recipe

servers:
  - url: http://localhost/api/v1

paths:
  /recipe/{id}:
    get:
      tags: [Recipe]
      summary: Get a recipe by ID
      parameters:
        - in: path
          name: id
          schema: { type: integer }
          required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Recipe' }

  # TODO: Authentication
  /ingredient/add:
    post:
      tags: [Fridge]
      summary: Add an ingredient to a virtual fridge
      description:
        Add `amount` of `ingredientId` to `fridgeId`.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fridgeId: { type: number, example: 1234 }
                ingredientId: { type: number, example: 1234 }
                amount: { type: number, example: 100 }
              required: [fridgeId, ingredientId, amount]
              additionalProperties: false
      responses:
        "204":
          description: No Content


components:
  schemas:
    Unit:
      enum:
        - none
        - whole
        - ml
        - g
      example: g

    Recipe:
      type: object
      properties:
        id: { type: integer, example: 12345 }
        name: { type: string, example: 'Chicken Pie' }
        directions: { type: string, example: "The great thing about chicken pie is that you don't need to know how to make it, just get some chicken. And put it in a pie."}
        link: { type: string, example: 'example.com' }
        ingredients:
          type: array
          items: { $ref: '#/components/schemas/IngredientEntry' }
      required: [id, name, directions, link, ingredients]
      additionalProperties: false

    Ingredient:
      type: object
      properties:
        id: { type: integer, example: 12345 }
        name: { type: string, example: 'Chicken' }
        preferredUnit: { $ref: '#/components/schemas/Unit' }
      required: [name, id, preferredUnit]
      additionalProperties: false

    IngredientEntry:
      type: object
      properties:
        ingredient: { $ref: '#/components/schemas/Ingredient' }
        amount: { type: number, example: 250 }
        originalLine: { type: string, example: '250g of chicken' }
      required: [ingredient, originalLine]
      additionalProperties: false
