import { Link } from 'react-router-dom'
import React from 'react'

import { type components } from '../types/api.generated'
import getRecipeUrl from '../utils/getRecipeUrl'

type MadeRecipe = components['schemas']['MadeRecipe']

export interface HistoryItemProps {
  rowStyle?: string
  cellStyle?: string
  madeRecipe: MadeRecipe
}

/**
 * An individual item in a user's history.
 * Intended to be used in the table generated by History and
 * is unlikely to be useful outside of that context.
 */
export default function HistoryItem (props: HistoryItemProps): React.JSX.Element {
  const peopleServed = props.madeRecipe.users.map(user => user.name).join(', ')

  // Convert the ISO date returned by the API to a string in the user's locale.
  // I.e., UK English will format the date as DD/MM/YYYY while US English will format it as MM/DD/YYYY.
  const dateMade = new Date(props.madeRecipe.dateMade).toLocaleDateString(/* user locale */ undefined, {
    weekday: 'short',
    day: 'numeric',
    month: 'short',
    year: 'numeric'
  })

  return (
    <tr className={props.rowStyle}>
      <td className={props.cellStyle}>
        <Link to={getRecipeUrl(props.madeRecipe.recipe.id)}>
          {props.madeRecipe.recipe.name}
        </Link>
      </td>
      <td className={props.cellStyle}>{peopleServed}</td>
      <td className={props.cellStyle}>{dateMade}</td>
    </tr>
  )
}
