---
# Build on push
name: Build
on: push
jobs:
  build_report:
    runs-on: ubuntu-latest
    name: Build Report
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: report/CHEFCookingHelper.tex
          work_in_root_file_dir: true
          latexmk_shell_escape: true
          latexmk_use_xelatex: true
          continue_on_error: true
      - uses: actions/upload-artifact@v4
        with:
          name: report
          path: report/CHEFCookingHelper.pdf
