---
# Lint all files on push
name: ESLint
on: push
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Install Modules
        run: npm install --save-dev
      - name: Install backend dependencies
        run: |
          cd app/backend
          npm install --save-dev
      - name: Install frontend dependencies
        run: |
          cd app/frontend
          npm install --save-dev
      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
